name: Sync LangChain    

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: LangChain  # 切换到你的 LangChain 分支

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Sync Fork
      run: |
        git remote add upstream https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain.git
        git fetch upstream
        git reset --hard upstream/main
        git rm -r --cached .github/workflows
        git commit -m "Remove workflow files before sync"
        git push origin LangChain --force
